baseURL = 'https://mikachou.github.io/'
languageCode = 'en-us'
title = "Michael's page"
theme = 'hugo-blog-awesome'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[params]
  mainSections = []

[params.author]
  intro = "Hi I'm Michael, Software Engineer"
  name = 'Michael Schuh'
  description = '''
  I build reliable systems, streamline workflows with <br>
  CI/CD, and develop modern web applications. <br>
  With 16+ years of experience,
  I enjoy turning complex problems into maintainable solutions.<br>
  <br>
  <a href="/resume/">View Resume</a>
  &nbsp;
  <a href="https://github.com/mikachou">Github</a>
  '''

[[params.socialIcons]]
name = "github"
url = "https://github.com/mikachou"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/michael-schuh-97600765/"

